version: "3.7"

services:
  hospital_db:
    restart: always
    image: postgres:alpine
    container_name: hospital_database
    ports:
      - 5432:5432
    env_file:
      - database.env

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

